se agrego el fallo del pipeline si encuentra criticidad media

diff --git a/.github/workflows/sast.yml b/.github/workflows/sast.yml
--- a/.github/workflows/sast.yml
+++ b/.github/workflows/sast.yml
@@ -29,3 +29,17 @@ jobs:
             #-Dsonar.verbose= # optional, default is false
           # When you need the analysis to take place in a directory other than the one from which it was launched, default is .
           projectBaseDir: .
+      - name: Wait for SonarCloud analysis to finish
+        run: |
+          echo "Waiting for SonarCloud analysis to finish"
+          sleep 20  # Espera de 20 segundos para que SonarCloud termine el análisis (ajustable)
+
+      - name: Check SonarCloud Quality Gate
+        run: |
+          echo "Checking SonarCloud Quality Gate status..."
+          quality_gate_status=$(curl -s -u "${{ secrets.SONAR_TOKEN }}:" "https://sonarcloud.io/api/qualitygates/project_status?projectKey=PabloCea123_laboratorio-final" | jq -r .projectStatus.status)
+          echo "Quality Gate status: $quality_gate_status"
+          if [ "$quality_gate_status" != "OK" ]; then
+            echo "Quality Gate failed. Failing the build."
+            exit 1
+          fi
